spring:
  application:
    name: "gatewayserver"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud: #eureka keşif sunucusuna bağlan ve mikroservisler hakkındaki ayrıntıları al
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

management: #actuator icin dsardan sunucu durumunu takip etmek icin api acar
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gateway Server Application"
    version: "1.0.0"

logging:
  level:
    com:
      micro:
        gatewayserver: DEBUG

